### ISSUE TITLE
Error when weaving DDataShardCoordinator from com.typesafe.akka:akka-cluster-sharding_2.13:2.6.8 

### ISSUE THREAD

**Issue by contrapost** [kontainers/micrometer-akka#84]
Hello,

We are using Java 11 and getting the following error when aspectj is trying to weave DDataShardCoordinator from com.typesafe.akka:akka-cluster-sharding_2.13:2.6.8:
```
[AppClassLoader@3b192d32] abort trouble in: 
akka.cluster.sharding.DDataShardCoordinator -- (ClassGenException) java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
org.aspectj.apache.bcel.generic.ClassGenException: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
    at org.aspectj.apache.bcel.generic.Instruction.readInstruction(Instruction.java:233)
    at org.aspectj.apache.bcel.generic.InstructionList.<init>(InstructionList.java:189)
    at org.aspectj.apache.bcel.generic.MethodGen.<init>(MethodGen.java:212)
    at org.aspectj.weaver.bcel.LazyMethodGen.initialize(LazyMethodGen.java:372)
    at org.aspectj.weaver.bcel.LazyMethodGen.markAsChanged(LazyMethodGen.java:540)
    at org.aspectj.weaver.bcel.LazyMethodGen.getBody(LazyMethodGen.java:929)
    at org.aspectj.weaver.bcel.BcelClassWeaver.findSuperOrThisCall(BcelClassWeaver.java:2626)
    at org.aspectj.weaver.bcel.BcelClassWeaver.matchInit(BcelClassWeaver.java:2716)
    at org.aspectj.weaver.bcel.BcelClassWeaver.match(BcelClassWeaver.java:2654)
    at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:483)
    at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:103)
    at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1713)
    at org.aspectj.weaver.bcel.BcelWeaver.weaveWithoutDump(BcelWeaver.java:1657)
    at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1422)
    at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1196)
    at org.aspectj.weaver.tools.WeavingAdaptor.getWovenBytes(WeavingAdaptor.java:551)
    at org.aspectj.weaver.tools.WeavingAdaptor.weaveClass(WeavingAdaptor.java:387)
    at org.aspectj.weaver.loadtime.Aj.preProcess(Aj.java:116)
    at org.aspectj.weaver.loadtime.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:51)
    at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
    at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
    at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
    at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at akka.cluster.sharding.ShardCoordinator$.props(ShardCoordinator.scala:68)
    at akka.cluster.sharding.ClusterShardingGuardian$$anonfun$receive$1.$anonfun$applyOrElse$1(ClusterSharding.scala:787)
    at scala.Option.getOrElse(Option.scala:201)
    at akka.cluster.sharding.ClusterShardingGuardian$$anonfun$receive$1.applyOrElse(ClusterSharding.scala:780)
    at akka.actor.Actor.aroundReceive(Actor.scala:537)
    at akka.actor.Actor.aroundReceive$(Actor.scala:535)
    at akka.cluster.sharding.ClusterShardingGuardian.aroundReceive(ClusterSharding.scala:696)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
    at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:547)
    at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
    at akka.monitor.instrumentation.ActorMonitors$TrackedActor.processMessage(ActorMonitor.scala:107)
    at akka.monitor.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:61)
    at akka.actor.ActorCell.invoke(ActorCell.scala:540)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
    at akka.dispatch.Mailbox.run(Mailbox.scala:231)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
```

**Comment by pjfanning** [comment]
this is more of an aspectjweaver issue than a micrometer-akka issue - are you using aspectjweaver 1.9.6 and micrometer-akka 0.12.1 ?

**Comment by contrapost** [comment]
@pjfanning, yes, we are using aspectjweaver 1.9.6 and micrometer-akka 0.12.1.

**Comment by pjfanning** [comment]
might be worth just extending the exclusion list in https://github.com/kontainers/micrometer-akka/blob/master/src/main/resources/META-INF/aop.xml

**Comment by contrapost** [comment]
@pjfanning, looks like it should work.

**Comment by pjfanning** [comment]
I published "0.12.2-SNAPSHOT" with an aop.xml that tries to exclude the akka-cluster classes

**Comment by contrapost** [comment]
@pjfanning, thanks, the fix helped.

**Comment by pjfanning** [comment]
0.12.2 release should be in maven repos soon
